### PR TITLE
issue resolution

### PR DESCRIPTION
**Pull request by Ychaima**

### CODE REVIEW

**Comment by Ychaima** [comment]
Hi Sami93 , 
Can you please take a look at this modification in the structure display . I think , it is better now. Actually , I have added some dependencies about datatable on angular . 
You need to install  before running "npm install datatables.net --save
                                 npm install datatables.net-dt --save
                                 npm install angular-datatables --save"
Best regards.

**Comment by sami93** [comment]
Hi Ychaima,

Sorry for my late reply. Could you make it responsive and order each column in the dataTAble.

Best,

**Comment by Ychaima** [comment]
Hello again Sami93 , 
I think everything is in order now , I have also optimized the search . 
Best regards. 
23848060_1473019639486306_484464346_o
23732368_10203729268068592_245350469_o

**Comment by sami93** [comment]
That's great.

**Pull request merged**
